[package]
name = "smol-evm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.12.2"
bytes = "1.5.0"
lazy_static = "1.4"
hex = "0.4"
